import path from "path";
import fs from "fs-extra";
import chalk from "chalk";

export async function initializeProject(projectPath: string): Promise<void> {
  const projectRoot = path.resolve(projectPath);

  try {
    console.log(
      chalk.blue(
        `Initializing Playwright LLM Test Case Generator in ${projectRoot}...`,
      ),
    );

    // Create directory structure
    const directories = [
      "tests",
      "generated",
      "page-objects",
      "utils",
      "audit/screenshots",
      ".github/workflows",
    ];

    for (const dir of directories) {
      const dirPath = path.join(projectRoot, dir);
      await fs.ensureDir(dirPath);
      console.log(chalk.green(`✓ Created directory: ${dir}`));
    }

    // Copy .env.example to project
    const envExampleContent = `# AI Model Configuration
AI_MODEL=claude                     # Options: claude, azure-openai, chatgpt, local
CLAUDE_API_KEY=                     # Required if using Claude (starts with sk-ant-)
AZURE_OPENAI_API_KEY=               # Required if using Azure OpenAI
AZURE_OPENAI_ENDPOINT=              # e.g. https://<resource>.openai.azure.com
AZURE_OPENAI_DEPLOYMENT=            # e.g. gpt-4o
AZURE_OPENAI_API_VERSION=2024-02-01 # Optional, defaults to 2024-02-01
CHATGPT_API_KEY=                    # Required if using ChatGPT (starts with sk-)
CHATGPT_MODEL=gpt-4o                # Optional, defaults to gpt-4o
LOCAL_LLM_URL=http://localhost:11434 # Required if using local LLM (Ollama default)
LOCAL_LLM_MODEL=llama3              # Required if using local LLM (e.g. llama3, mistral, codellama)

# Playwright Configuration
BROWSER=chromium
HEADLESS=true

# Execution Configuration
TIMEOUT=30000
RETRIES=1
VIDEO=retain-on-failure
`;
    const targetEnvPath = path.join(projectRoot, ".env.example");
    await fs.writeFile(targetEnvPath, envExampleContent);

    // Create .env file if it doesn't exist
    const envPath = path.join(projectRoot, ".env");
    if (!fs.existsSync(envPath)) {
      await fs.writeFile(envPath, envExampleContent);
      console.log(chalk.green("✓ Created .env file"));
    }

    // Create playwright.config.ts
    const playwrightConfig = `import { defineConfig, devices } from '@playwright/test';
import { config } from 'dotenv';
config();

export default defineConfig({
  testDir: './generated',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : 4,
  reporter: 'html',
  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: (process.env.VIDEO || 'retain-on-failure') as 'off' | 'on' | 'retain-on-failure' | 'on-first-retry',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ].filter(p => !process.env.BROWSER || p.name === (process.env.BROWSER || 'chromium')),
});
`;
    await fs.writeFile(
      path.join(projectRoot, "playwright.config.ts"),
      playwrightConfig,
    );
    console.log(chalk.green("✓ Created playwright.config.ts"));

    // Create package.json for the generated project
    const packageJson = {
      name: "playwright-tests",
      version: "1.0.0",
      description:
        "Playwright tests generated by @zhiweiliu/playwright-generator",
      scripts: {
        test: "playwright test",
        "test:case": "playwright test --grep",
        "test:debug": "playwright test --debug --project=chromium --grep",
        "test:headed": "playwright test --headed --grep",
        "test:browser": "playwright test --grep",
        "test:video": "playwright test --grep",
        report: "node report.js",
      },
      devDependencies: {
        "@playwright/test": "^1.40.0",
        "@types/node": "^20.11.0",
        dotenv: "^16.3.1",
      },
      keywords: ["playwright", "testing", "automation"],
      author: "",
      license: "MIT",
    };

    await fs.writeFile(
      path.join(projectRoot, "package.json"),
      JSON.stringify(packageJson, null, 2),
    );
    console.log(chalk.green("✓ Created package.json"));

    // Add tsconfig so process/types are recognized in playwright.config.ts
    const tsconfig = {
      compilerOptions: {
        target: "ES2020",
        module: "nodenext",
        lib: ["ES2020", "DOM"],
        strict: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        skipLibCheck: true,
        moduleResolution: "nodenext",
        types: ["node", "playwright/test"],
      },
      include: ["**/*.ts"],
    };

    await fs.writeFile(
      path.join(projectRoot, "tsconfig.json"),
      JSON.stringify(tsconfig, null, 2),
    );
    console.log(chalk.green("✓ Created tsconfig.json"));

    // Create sample test cases
    const saucedemoSampleContent = `# Test Case: Complete Purchase Flow

[TC-SAMPLE-0001] [SMOKE] [PURCHASE] [END-TO-END]

## Complete e-commerce purchase flow from login to order confirmation

- Given the user navigates to the SauceDemo login page at https://saucedemo.com
- When the user enters "standard_user" as the username
- And the user enters "secret_sauce" as the password
- And the user clicks the "Login" button
- Then the user should be redirected to the products page
- And the page title should contain "Products"

- When the user clicks on the "Sauce Labs Backpack" product
- Then the product details page should open
- And the product name should be "Sauce Labs Backpack"
- And the product price should be displayed

- When the user clicks the "Add to Cart" button
- Then the cart icon should show "1" item
- And the "Add to Cart" button should change to "Remove"

- When the user clicks the cart icon in the top right
- Then the cart page should open
- And the "Sauce Labs Backpack" should be listed in the cart
- And the quantity should be 1
- And the price should match the product page

- When the user clicks the "Checkout" button
- Then the checkout information page should open

- When the user enters "John" as the first name
- And the user enters "Doe" as the last name
- And the user enters "12345" as the zip code
- And the user clicks the "Continue" button
- Then the checkout overview page should open
- And the item total should be calculated correctly
- And the tax should be applied
- And the total amount should be displayed

- When the user clicks the "Finish" button
- Then the order confirmation page should open
- And a success message "Thank you for your order!" should be displayed
- And the order number should be shown

# Test Case: Product Browsing and Cart Management

[TC-SAMPLE-0002] [REGRESSION] [BROWSING] [CART]

## Browse products, sort items, and manage cart contents

- Given the user is logged in to SauceDemo with valid credentials
- When the user is on the products page
- Then all products should be displayed in a grid layout
- And each product should show name, price, and "Add to Cart" button

- When the user clicks the sort dropdown
- Then sorting options should be displayed: Name (A to Z), Name (Z to A), Price (low to high), Price (high to low)

- When the user selects "Name (A to Z)" from the sort dropdown
- Then products should be sorted alphabetically by name in ascending order
- And the first product should be "Sauce Labs Backpack"

- When the user selects "Name (Z to A)" from the sort dropdown
- Then products should be sorted alphabetically by name in descending order
- And the first product should be "Test.allTheThings() T-Shirt (Red)"

- When the user selects "Price (low to high)" from the sort dropdown
- Then products should be sorted by price in ascending order
- And the first product should be the cheapest item

- When the user selects "Price (high to low)" from the sort dropdown
- Then products should be sorted by price in descending order
- And the first product should be the most expensive item

- When the user clicks "Add to Cart" on the first product in the sorted list
- Then the cart icon should update to show "1"
- And that product's button should show "Remove"

- When the user clicks "Add to Cart" on the second product in the sorted list
- Then the cart icon should update to show "2"
- And both products' buttons should show "Remove"

- When the user clicks the cart icon
- Then the cart page should open
- And both selected products should be listed
- And the quantities should be 1 for each
- And the total price should be the sum of both items

- When the user clicks "Remove" next to the first product
- Then that product should be removed from the cart
- And the cart should show only the second product
- And the cart icon should show "1"

- When the user clicks "Continue Shopping"
- Then the user should return to the products page
- And the cart icon should still show "1"

- When the user clicks the cart icon again
- Then the cart should still contain the remaining product
- And the user can proceed with checkout if desired
`;

    await fs.writeFile(
      path.join(projectRoot, "tests", "saucedemo-samples.test.md"),
      saucedemoSampleContent,
    );
    console.log(chalk.green("✓ Created SauceDemo sample test cases"));

    // Create report.js — kills port 9324 then launches playwright show-report
    const reportScript = `const { execSync, spawn } = require('child_process');
const PORT = 9324;

// Kill any process already using the port (cross-platform)
try {
  if (process.platform === 'win32') {
    const result = execSync('netstat -ano | findstr :' + PORT, { encoding: 'utf8', stdio: ['pipe','pipe','ignore'] });
    const lines = result.trim().split('\\n');
    const pids = [...new Set(lines.map(l => l.trim().split(/\\s+/).pop()).filter(Boolean))];
    pids.forEach(pid => { try { execSync('taskkill /PID ' + pid + ' /F', { stdio: 'ignore' }); } catch (_) {} });
  } else {
    execSync('lsof -ti:' + PORT + ' | xargs kill -9', { stdio: 'ignore', shell: true });
  }
} catch (_) {}

// Small delay to ensure port is released
setTimeout(() => {
  const proc = spawn(
    process.platform === 'win32' ? 'npx.cmd' : 'npx',
    ['playwright', 'show-report', '--port', String(PORT)],
    { stdio: 'inherit', shell: false }
  );
  proc.on('error', err => { console.error('Failed to start report server:', err.message); });
}, 500);
`;
    await fs.writeFile(path.join(projectRoot, "report.js"), reportScript);
    console.log(chalk.green("✓ Created report.js"));
    // Create GitHub Actions workflow
    const workflow = `name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
`;

    await fs.writeFile(
      path.join(projectRoot, ".github/workflows/playwright-tests.yml"),
      workflow,
    );
    console.log(chalk.green("✓ Created GitHub Actions workflow"));

    // Create .gitignore if it doesn't exist
    const gitignorePath = path.join(projectRoot, ".gitignore");
    if (!fs.existsSync(gitignorePath)) {
      const gitignore = `node_modules/
dist/
.DS_Store
.env
.env.local
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
playwright-report/
blob-report/
playwright/.cache/
audit/screenshots/*
`;
      await fs.writeFile(gitignorePath, gitignore);
      console.log(chalk.green("✓ Created .gitignore"));
    }

    console.log(chalk.green.bold("\\n✓ Project initialized successfully!"));
    console.log(chalk.cyan("\\nNext steps:"));
    console.log("1. Install dependencies: npm install");
    console.log("2. Write test cases in the tests/ folder");
    console.log(
      "3. Run: npx playwright-generator generate --tc TC-SAMPLE-0001",
    );
    console.log("4. Edit .env with your API credentials");
    console.log("5. Run tests: npm test");
  } catch (error) {
    console.error(chalk.red("Error initializing project:"), error);
    throw error;
  }
}
