import path from "path";
import fs from "fs-extra";
import chalk from "chalk";
import configManager from "../config";

export async function initializeProject(projectPath: string): Promise<void> {
  const projectRoot = path.resolve(projectPath);

  try {
    console.log(
      chalk.blue(
        `Initializing Playwright LLM Test Case Generator in ${projectRoot}...`,
      ),
    );

    // Create directory structure
    const directories = [
      "tests",
      "generated",
      "page-objects",
      "utils",
      "audit/screenshots",
      ".github/workflows",
    ];

    for (const dir of directories) {
      const dirPath = path.join(projectRoot, dir);
      await fs.ensureDir(dirPath);
      console.log(chalk.green(`✓ Created directory: ${dir}`));
    }

    // Copy .env.example to project
    const envExamplePath = path.join(__dirname, "../../.env.example");
    const targetEnvPath = path.join(projectRoot, ".env.example");

    if (fs.existsSync(envExamplePath)) {
      await fs.copy(envExamplePath, targetEnvPath);
    }

    // Create .env file if it doesn't exist
    const envPath = path.join(projectRoot, ".env");
    if (!fs.existsSync(envPath)) {
      await fs.writeFile(envPath, fs.readFileSync(targetEnvPath, "utf-8"));
      console.log(chalk.green("✓ Created .env file"));
    }

    // Create playwright.config.ts
    const playwrightConfig = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './generated',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : 4,
  reporter: 'html',
  use: {
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],

  webServer: {
    command: 'npm run server',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
});
`;
    await fs.writeFile(
      path.join(projectRoot, "playwright.config.ts"),
      playwrightConfig,
    );
    console.log(chalk.green("✓ Created playwright.config.ts"));

    // Create package.json for the generated project
    const packageJson = {
      name: "playwright-tests",
      version: "1.0.0",
      description:
        "Playwright tests generated by @zhiweiliu/playwright-generator",
      scripts: {
        test: "playwright test",
        "test:tag": "playwright test --grep",
        "test:case": "playwright test --grep",
        "test:debug": "playwright test --debug",
        "test:headed": "playwright test --headed",
        "test:browser": "playwright test --project",
        report: "playwright show-report",
        server: 'echo "Add your server startup command here"',
      },
      devDependencies: {
        "@playwright/test": "^1.40.0",
      },
      keywords: ["playwright", "testing", "automation"],
      author: "",
      license: "MIT",
    };

    await fs.writeFile(
      path.join(projectRoot, "package.json"),
      JSON.stringify(packageJson, null, 2),
    );
    console.log(chalk.green("✓ Created package.json"));

    // Create example test case
    const exampleTestCase = `# [TC-0001] [SMOKE] [LOGIN]

## Test: User logs in with valid credentials

Given the user is on the login page
When the user enters valid username and password
And clicks the login button
Then the user should be redirected to the dashboard
And the user name should be displayed in the header
`;

    await fs.writeFile(
      path.join(projectRoot, "tests", "example.test.md"),
      exampleTestCase,
    );
    console.log(chalk.green("✓ Created example test case"));

    // Create GitHub Actions workflow
    const workflow = `name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
`;

    await fs.writeFile(
      path.join(projectRoot, ".github/workflows/playwright-tests.yml"),
      workflow,
    );
    console.log(chalk.green("✓ Created GitHub Actions workflow"));

    // Create .gitignore if it doesn't exist
    const gitignorePath = path.join(projectRoot, ".gitignore");
    if (!fs.existsSync(gitignorePath)) {
      const gitignore = `node_modules/
dist/
.DS_Store
.env
.env.local
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
playwright-report/
blob-report/
playwright/.cache/
audit/screenshots/*
`;
      await fs.writeFile(gitignorePath, gitignore);
      console.log(chalk.green("✓ Created .gitignore"));
    }

    console.log(chalk.green.bold("\\n✓ Project initialized successfully!"));
    console.log(chalk.cyan("\\nNext steps:"));
    console.log("1. Edit .env with your API credentials");
    console.log("2. Write test cases in the tests/ folder");
    console.log("3. Run: npx playwright-generator generate --tc TC-0001");
    console.log("4. Install dependencies: npm install");
    console.log("5. Run tests: npm test");
  } catch (error) {
    console.error(chalk.red("Error initializing project:"), error);
    throw error;
  }
}
